### ISSUE TITLE
[feature] backend file model

### ISSUE THREAD

**Issue by sonnyding1** [sonnyding1/CS35L-Egg#17]
The file model should have: file name, content, username (the name of the owner of the file)

**Comment by tahaelhal** [comment]
File model has been updated. It now is a shell with the proper fields needed. Tested the create and delete functions locally and they worked, but I am not so sure how to test with the req.session situation. 
Before merging with main I would like to have the file uploads checked out. I have some leads on that. 
Check my branch for the latest version
