### ISSUE TITLE
[feature] comment API endpoints

### ISSUE THREAD

**Issue by sonnyding1** [sonnyding1/CS35L-Egg#30]
CRUD operations for the comment model, including:

- create a new comment
- get all comments of a file
- update a comment
- delete a comment

**Comment by tahaelhal** [comment]
create and delete a comment and get all comments of a file are up
- will need more identifiers to delete specific comments, but for now we delete the oldest comment
- get all comments of a file --> comments are displayed when you get a file. I can add an independent get to just fetch the comments

**Comment by sonnyding1** [comment]
we only need to fetch all the comments along with the file though, so it should be fine

**Comment by tahaelhal** [comment]
Comment model has been finalized for create, delete, and get.
Will be adding update functionality soon for all models.
